### PR TITLE
Traditional Chinese translation.

### PR DESCRIPTION
**Pull request by audreyt**
Based on the work from @limechord — please assign the `zh-hant` language code for this work. Thanks! :rainbow:

### CODE REVIEW

**Comment by ncase** [comment]
Hi @audreyt , thanks for doing this! However, pulling this would change the main English version. Could you fork this repo, and have a gh-pages branch so that GitHub automatically creates a website for it? When you do that, _then_ I can link to your Traditional Chinese translation from the main site!

(Sorry the process is such a hassle – this is an old project from 2014, long before I knew or even thought about translate-ability. My newer projects are, hopefully, less annoying to translate)

**Comment by audreyt** [comment]
Sure! The site is now at https://audreyt.github.io/polygons/

**Comment by ncase** [comment]
Sweet, thanks @audreyt! I'm currently away for a conference but I'll add that link to the main page next week. Many thanks again! :D

**Comment by ncase** [comment]
@audreyt : Link to your translation has been added! https://github.com/ncase/polygons/commit/610751400c5cfb14ac65aabf6735fc14b3284c91

**Pull request closed without merging**
