### PR TITLE
Master

### PR DESCRIPTION
**Pull request by setcz**

### CODE REVIEW

**Comment by ncase** [comment]
Thank you so much for this! Your translation is now hosted at http://ncase.me/polygons-cs/, and linked to from the default (English) site. :)

**Comment by setcz** [comment]
Sorry!

It is not finished yet. I am not used to use git and didnt want to send it
to you yet, it was a mistake. :)

We plan to finish it in a few days and then host it on Czech domain
www.bajkaotvarech.cz

Can you please remove it from your page now? We will let you know when it
is finished.

Sorry for the mess:)

Martin
Dne 18. 4. 2015 13:22 napsal uživatel "Nicky Case" <notifications@github.com

**Comment by ncase** [comment]
Ah, okay! It's been removed from the default/english page now. Let me know whenever the new translation is done! (I might not be responsive next week, since I'll be at a conference)

**Comment by setcz** [comment]
Hi Nicky,

we finally managed to finish the translation, it is up and running here -
www.bajkaotvarech.cz ("bajka o tvarech" means "parable of polygons" in
Czech).

If you could add a link to the main English page, it would be great.

Have a great day!

Martin

**Comment by setcz** [comment]
And can you please remove this version from the web -
http://ncase.me/polygons-cs/ - it is unfinished and showing up in google:).

Also I have just noticed that I have been sending the previous email to
some strange github adress, so I just in case added your normal email (if
you didn't receive the previous email, I wrote you:

*We finally managed to finish the translation, it is up and running here
- www.bajkaotvarech.cz http://www.bajkaotvarech.cz/ ("bajka o tvarech"
  means "parable of polygons" in Czech).*

_If you could add a link to the main English page, it would be great._ )

Cheers!

Martin

On Sun, May 31, 2015 at 11:05 AM, Martin Křivánek <martin.krivanek@gmail.com

**Pull request closed without merging**
